export {
  addSongToPlaylist,
  createPlaylist,
  deletePlaylist,
  getAlbum,
  getAlbums,
  getAllSongs,
  getArtist,
  getArtistTracks,
  getArtists,
  getCoverUrl,
  getPlaylist,
  getPlaylists,
  getRandomAlbums,
  getRandomSongs,
  getRecentlyPlayed,
  getStarred,
  getStreamUrl,
  removeSongFromPlaylist,
  recordRecentlyPlayed,
  searchNavidrome,
  starSong,
  unstarSong,
  updatePlaylist,
} from "./musicdeck";
