import type { UnifiedSearchResult } from "./search.js";
import type { SourceCandidate } from "./source-discovery.js";
import type { AcquiredFile } from "./acquisition.js";

export type DownloadRequest = {
  spotifyTrackUrl?: string;
  spotifyTrackId?: string;
  query?: string;
  sourceUrl?: string;
  outputDirectory: string;
  /** Shared library root for playlist downloads; metadata stays in outputDirectory. */
  libraryRoot?: string;
  filenameTemplate?: string;
  /** Optional playlist manifest generated by spotDL in outputDirectory. */
  playlistM3uName?: string;
  /** Include additional keyless audio sources when retrying a missing playlist song. */
  broadenAudioSearch?: boolean;
  /** Isolate recovery providers: one failed download must not suppress the next source. */
  audioProvider?: "soundcloud" | "youtube" | "youtube-music";
  /** Verified playlist identity, used without repeating Spotify metadata searches. */
  canonicalMetadata?: SpotifyImportTrackMetadata;
  timeoutMs?: number;
  requestedTrack?: UnifiedSearchResult;
  candidate?: SourceCandidate;
};

export type DownloaderCapabilities = {
  spotifyTrack: boolean;
  textSearch: boolean;
  directUrl: boolean;
  album: boolean;
  playlist: boolean;
  metadata: boolean;
};

export type DownloadStage =
  | "downloading"
  | "converting"
  | "processing"
  | "tagging"
  | "importing";

export type DownloadProgress = {
  jobId?: string;
  bytesDownloaded?: number;
  totalBytes?: number;
  percent?: number;
  speedBytesPerSecond?: number;
  stage?: DownloadStage;
  message?: string;
};

export type DownloadContext = {
  jobId: string;
  tmpDir: string;
  signal: AbortSignal;
  onProgress?: (progress: DownloadProgress) => void;
};

export type DownloadErrorCode =
  | "retryable"
  | "non-retryable"
  | "rate-limited"
  | "authentication-failed"
  | "not-found"
  | "invalid-input"
  | "cancelled"
  | "executable-missing"
  | "general";

export type SpotifyImportTrackMetadata = {
  position: number; url: string; title: string; artist: string; artists?: string[];
  duration: number; album?: string; albumArtist?: string; year?: string;
  artworkUrl?: string; isrc?: string; albumId?: string;
  trackNumber?: number; tracksCount?: number; discNumber?: number; discCount?: number;
  genres?: string[]; explicit?: boolean; publisher?: string; releaseDate?: string;
};

export type DownloadDiagnostics = {
  strategy: "spotify" | "cached-metadata" | "deezer-assisted";
  searchQuery?: string;
  metadataLookup?: string;
  audioProvider?: DownloadRequest["audioProvider"];
  /** Bounded, credential-redacted output retained in the durable import manifest. */
  output: string;
};

export type DownloadResult = {
  status: "completed" | "failed" | "cancelled";
  files: AcquiredFile[];
  /** spotDL's saved playlist metadata, including tracks whose audio failed. */
  playlistTracks?: SpotifyImportTrackMetadata[];
  playlistLength?: number;
  diagnostics?: DownloadDiagnostics;
  error?: {
    code: DownloadErrorCode;
    message: string;
  };
};

/**
 * DownloaderAdapter represents a standalone media download backend
 * (such as spotDL, authorized HTTP, or archive-org downloaders).
 * It abstracts executable invocation, progress events, cancellation, and metadata tagging.
 */
export interface DownloaderAdapter {
  readonly id: string;
  readonly name: string;
  readonly capabilities: DownloaderCapabilities;

  canHandle(request: DownloadRequest): boolean | Promise<boolean>;

  download(
    request: DownloadRequest,
    context: DownloadContext
  ): Promise<DownloadResult>;

  /** Resolve Spotify playlist metadata without downloading any audio. */
  fetchPlaylistTracks?(playlistUrl: string, context: DownloadContext): Promise<DownloadResult>;
  /** Recover incomplete source metadata without downloading audio. */
  resolveTrackMetadata?(track: NonNullable<DownloadResult["playlistTracks"]>[number], context: DownloadContext): Promise<NonNullable<DownloadResult["playlistTracks"]>[number] | null>;

  /** Optional playlist title, description, and cover from a metadata provider. */
  fetchPlaylistDetails?(playlistId: string): Promise<{ title?: string; description?: string | null; artworkUrl?: string | null } | null>;

  cancel?(jobId: string): Promise<void> | void;

  test?(): Promise<{ ok: boolean; message?: string }>;

  /** Applies runtime configuration (e.g. credentials, binary paths) without recreating the adapter. */
  configure?(options: Record<string, unknown>): void;
}

export class DownloaderAdapterRegistry {
  private readonly adapters = new Map<string, DownloaderAdapter>();

  register(adapter: DownloaderAdapter): void {
    this.adapters.set(adapter.id, adapter);
  }

  unregister(adapterId: string): void {
    this.adapters.delete(adapterId);
  }

  get(adapterId: string): DownloaderAdapter | undefined {
    return this.adapters.get(adapterId);
  }

  list(): DownloaderAdapter[] {
    return [...this.adapters.values()];
  }

  getAll(): DownloaderAdapter[] {
    return this.list();
  }

  async findAdapters(request: DownloadRequest): Promise<DownloaderAdapter[]> {
    const matching: DownloaderAdapter[] = [];
    for (const adapter of this.adapters.values()) {
      try {
        if (await adapter.canHandle(request)) {
          matching.push(adapter);
        }
      } catch {}
    }
    return matching;
  }
}
